# Generated by Django 2.2.11 on 2020-05-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20200514_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
