# Generated by Django 2.2.11 on 2020-05-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_productvariationmanager'),
        ('carts', '0009_cartitem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='varitaion',
            field=models.ManyToManyField(to='products.ProductVariation'),
        ),
    ]
