# Generated by Django 2.2.11 on 2020-05-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_cartitem_varitaion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='varitaion',
            new_name='variation',
        ),
    ]
