# Generated by Django 2.2.11 on 2020-05-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200507_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='products/images/default.png', upload_to='products/images'),
        ),
    ]
