# Generated by Django 2.2.11 on 2020-05-18 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productvariation_productvariationmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariationManager',
        ),
    ]
